image:
  file: docker/gitpod.Dockerfile

tasks:
  - name: Open cypress
    command: |
      gp sync-await install
      npx cypress install --force
      npx cypress verify
      npx cypress infoyarn cypress:open
    openMode: tab-after
  - name: Install and run dev server
    init: |
      yarn --force
      gp sync-done install
    command: yarn start
    openMode: tab-before
ports:
  - port: 3000
    onOpen: open-preview
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
