image:
  file: docker/gitpod.Dockerfile

tasks:
  - name: Install and run dev server
    init: |
      yarn --force
      gp sync-done install
    command: yarn start
  - name: Open cypress
    init: gp sync-await install
    command: yarn cypress:open
    openMode: tab-after
ports:
  - port: 3000
    onOpen: open-preview
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser