name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    environment: TEST
    runs-on: ubuntu-20.04
    container: cypress/included:8.3.1
    strategy:
      fail-fast: false
    matrix:
      # run 3 copies of the current job in parallel
      containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: yarn install
      - name: Cypress run
        uses: cypress-io/github-action@v2.9.7
        with:
          group: "Github actions group"
          browser: chrome
          parallel: true
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
